"""Fresh start

Revision ID: e17a9d440ea9
Revises: 
Create Date: 2024-10-13 20:18:49.122894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17a9d440ea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.drop_index('ix_chat_models_id', table_name='chat_model')
    op.drop_index('ix_chat_models_name', table_name='chat_model')
    op.create_index(op.f('ix_chat_model_id'), 'chat_model', ['id'], unique=False)
    op.create_index(op.f('ix_chat_model_name'), 'chat_model', ['name'], unique=False)
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_template_id'), 'prompt_template', ['id'], unique=False)
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tool_id'), 'tool', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_id'), table_name='tool')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_index(op.f('ix_prompt_template_id'), table_name='prompt_template')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.drop_index(op.f('ix_chat_model_name'), table_name='chat_model')
    op.drop_index(op.f('ix_chat_model_id'), table_name='chat_model')
    op.create_index('ix_chat_models_name', 'chat_model', ['name'], unique=False)
    op.create_index('ix_chat_models_id', 'chat_model', ['id'], unique=False)
    op.drop_index(op.f('ix_category_id'), table_name='category')
    # ### end Alembic commands ###
